# Base Jekyll configuration

# Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

# Use _config.build.yml to override these settings on `grunt build`.

name: Coding-Standards
description: Coding Standards

author:
  name: kwaledesign
  email: sam@kwaledesign.com
  github: kwaledesign
  twitter: kwaledesign

# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: ['images', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', 'docs',
          'bower_components', 'sass']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: pretty

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Markdown library
markdown: maruku
# Markdown library options
# maruku:
  # use_tex:    false
  # use_divs:   false
  # png_engine: blahtex
  # png_dir:    images/latex
  # png_url:    /images/latex

# Use Pygments to highlight code blocks
pygments: true
